---
title: "Multilingual LCZ4r-QGIS Plugin"
description: >
  A collection of multiple languages that use the LCZ4r package.
author: "Max Anjos"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output:
    rmarkdown::html_vignette:
      code_folding: hide
    toc: true
    toc_float: TRUE
    toc_depth: 2
    number_sections: false
    highlight: "textmate"
    css: custom.css
vignette: >
  %\VignetteIndexEntry{Multilingual LCZ4r-QGIS Plugin}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{rmarkdown::render}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
#source("example_cards.R", local = TRUE)

card <- function(
  ...,
  class_card = NULL,
  class_card_body = NULL,
  class_card_title = NULL,
  class_card_footer = "text-end"
) {
  card_data <- list(...)
  htmltools::withTags(
    div(
      class = "col",
      div(
        class = c("card h-100 shadow-sm", class_card),
        a(
          href = card_data$link,
          img(
            src = card_data$image,
            class = "card-img-top",
            alt = paste0("Preview image of ", card_data$title)
          )
        ),
        div(
          class = c("card-body", class_card_body),
          h5(class = c("card-title", class_card_title), a(href = card_data$link, card_data$title)),
          if (!is.null(card_data$text)) div(
            class = "card-text text-muted fs-6",
            htmltools::HTML(commonmark::markdown_html(card_data$text))
          ),
        ),
        if (!is.null(card_data$footer)) div(
          class = c("card-footer", class_card_footer),
          htmltools::HTML(card_data$footer)
        )
      )
    )
  )
}

example_cards <- function(yml, group = NULL, class_row = "row-cols-1 row-cols-md-2 row-cols-lg-3") {
  examples <- if (is.list(yml)) {
    yml
  } else {
    yaml::read_yaml(yml)
  }

  examples <- purrr::keep(examples, function(x) x[["group"]] %in% group)
  examples <- purrr::transpose(examples)

  htmltools::tags$div(
    class = paste("row g-4", class_row),
    purrr::pmap(examples, card)
  )
}

```

```{css echo=FALSE}
.row > main { max-width: 100%; }
```

```{r example-cards-showcase}
example_cards("examples.yml", "showcase")
```


## Multilingual Plugins

Please, select your preferential language.

```{r example-cards-demo}
example_cards("examples.yml", "demo")
```


```{js echo=FALSE}
document.getElementById('main').classList = ''
```
