#' Download the LCZ map from LCZ Generator
#'
#' This function retrieves the LCZ map from LCZ Generator platform
#'
#' @param ID A code specifying the ID generated by LCZ Factsheet (e.g, "3110e623fbe4e73b1cde55f0e9832c4f5640ac21"). More details: \url{https://lcz-generator.rub.de/factsheets/3110e623fbe4e73b1cde55f0e9832c4f5640ac21/3110e623fbe4e73b1cde55f0e9832c4f5640ac21_factsheet.html}
#' @param isave_map Logical. Set to TRUE if you wish to save the resulting map as a raster TIFF file on your local machine.
#' @param band  Select the feature to use. The available options are: “lcz” and “lczFilter”. The default is "lczFilter".
#' @return A Terra raster TIFF file containing LCZ classes (1-17).
#'
#' @export
#'
#' @references
#' Demuzere, M., Kittner, J., Bechtel, B. (2021). LCZ Generator: a web application to create Local Climate Zone maps. Frontiers in Environmental Science 9:637455. https://doi.org/10.3389/fenvs.2021.637455
#'
#' @examples
#' \dontrun{
#' # Load the Rio de Janeiro map from LCZ Generator
#' my_lcz_map <- lcz_get_map_generator(ID = "3110e623fbe4e73b1cde55f0e9832c4f5640ac21")
#'
#' }
#'
#' @keywords LCZ, Local Climate Zone, urban climate, LCZ Generator

lcz_get_map_generator <- function(ID = "3110e623fbe4e73b1cde55f0e9832c4f5640ac21", band = "lczFilter", isave_map = FALSE) {
  # Validate inputs
  if (is.null(ID)) {
    stop("Error: provide correctly ID code. Please check it out in the LCZ Factsheet")
  }
  if (band != "lcz" && band != "lczFilter") {
    stop("The 'band' input must be either 'lcz' or 'lczFilter'.")
  }
  options(warn = -1)
  # Download the LCZ generator map
  lcz_download <- terra::rast(base::paste0("/vsicurl/", "https://lcz-generator.rub.de/factsheets/", ID, "/", ID, ".tif"))

  if (base::is.null(lcz_download)) {
    stop("This error might be due to server restrictions. In such cases, you may need to download the file manually using this link:
      https://lcz-generator.rub.de/submissions")
  }

  if(band == "lczFilter") {
    lcz_ras <- lcz_download$lczFilter
  } else {
    lcz_ras <- lcz_download$lcz
  }

  base::names(lcz_ras) <- "lcz"

  if (isave_map == TRUE) {
    # Create a folder name using paste0
    folder <- base::paste0("LCZ4r_output/")

    # Check if the folder exists
    if (!dir.exists(folder)) {
      # Create the folder if it does not exist
      base::dir.create(folder)
    }

    file <- base::paste0(getwd(), "/", folder, "lcz_map_generator.tif")
    terra::writeRaster(lcz_ras, file, overwrite = TRUE)
    base::message("Looking at your files in the path:", base::paste0(getwd(), "/", folder))
  }

  return(lcz_ras)
}
